### ISSUE TITLE
Plugin Cache not automatically removed after version bump

### ISSUE THREAD

**Issue by nikduvall** [netlify/plugins#120]
**Describe the bug**
Prior to the merge of [PR-119](https://github.com/netlify/plugins/pull/119), I had installed netlify-purge-cloudflare-on-deploy@1.0.7 via the Netlify UI.  I removed from the UI to create the new version 1.1.0 locally.  Now that the PR has been merged, when I re-add the plugin via the Netlify UI, the logs show the buildbot trying to deploy the old version.

**To Reproduce**
1.  Install a plugin via Netlify UI
2.  Successfully Re-deploy site with plugin
2.  Remove the plugin from your site via Netlify UI
3.  Update the plugin to a new version and deploy version change to [netlify/plugins/plugins.json](https://github.com/netlify/plugins/blob/master/plugins.json)
4.  Re-install the plugin via Netlify UI
5.  Attempt to Re-deploy site with plugin
6.  Note in build log that buildbot attempted to deploy old version of plugin

**Expected behavior**
* In this specific scenario, buildbot should detect that the plugin cache is stale and deploy new version.
* If it doesn't already exist, In the scenario where an already-installed plugin has been updated to a newer version, the Netlify UI should provide the user a collection of calls to action to minimally give them the option to stay on current version or upgrade to newer version with follow up calls to action to either deploy now or later.

**Evidence**
buildbot deploying cached version of plugin: [duvee-digital-team Build 5f1581769bd3240008f69ea9](https://app.netlify.com/teams/duvee-digital-team/builds/5f1581769bd3240008f69ea9)

**Comment by ehmicky** [comment]
Hi @nikduvall,

The `plugins.json` is part of a larger deployment process for the Netlify build infrastructure. Before making the plugins update available in production, we have few additional QA processes in place. However, we are working on automating that process, so that you don't need to wait for too long for updates to be available in production.

Thanks for the feedback!
