### ISSUE TITLE
Add community post about changes to `onSuccess` behaviour

### ISSUE THREAD

**Issue by erezrokah** [netlify/plugins#140]
Pending the upcoming change in `onSuccess` behaviour, we need to post it in the community.
Related to https://github.com/netlify/plugins/issues/134

**Comment by ehmicky** [comment]
We should also remember to post it to #internal-changelog

**Comment by verythorough** [comment]
Technically, the RSS feed for the Community Updates category will post to the changelog automatically!

**Comment by ehmicky** [comment]
This should be split into two different posts:
  1. Errors inside `onSuccess` and `onEnd` do not make the build fail anymore (released soon)
  2. `onSuccess` and `onEnd` now happens after deploy (WIP)

**Comment by ehmicky** [comment]
Post `1.` published at https://community.netlify.com/t/netlify-build-plugins-changes-to-how-errors-are-handled-in-onsuccess-and-onend-events/23535

Post `2.` in draft mode at https://community.netlify.com/t/netlify-build-plugins-changes-to-when-onsuccess-and-onend-are-invoked-during-the-build-cycle/23489

**Comment by cdeleeuwe** [comment]
@ehmicky do you know if the new onSuccess behaviour is already in production? Thanks

**Comment by ehmicky** [comment]
Hi @cdeleeuwe!
It is in production for a single plugin (Algolia) at the moment. We are working on extending it to every plugin and users. Once this is done, we will publish the post `2.` mentioned above.

**Comment by verythorough** [comment]
This update was posted last month: 
https://community.netlify.com/t/netlify-build-plugins-changes-to-when-onsuccess-and-onend-are-invoked-during-the-build-cycle/23489

And the changes are now fully released!
