### ISSUE TITLE
Add guidelines for plugin authors seeking inclusion in the list

### ISSUE THREAD

**Issue by verythorough** [netlify/plugins#20]
@ehmicky has summarized common plugin issues in a [separate issue comment](https://github.com/netlify/build/issues/1068#issuecomment-605276244). We can convert this information into a checklist of items needed before submitting a PR to add a plugin to the list.

We could add the content to the README (or contributor guide?), and could also benefit from putting the checklist into a PR template.

Auto-linting would be great, too, but until then, guidance works. :)

**Comment by ehmicky** [comment]
Absolutely!
We could add it to the PR template too with a bunch of checkboxes.
