### ISSUE TITLE
Discussion: consistent plugins names 

### ISSUE THREAD

**Issue by erezrokah** [netlify/plugins#208]
Raised from an internal Slack conversation:
https://netlify.slack.com/archives/C012GT6MYKU/p1611611766161400

Some of our plugins have names ending with `plugin` which leads to this message when installing them:
![image](https://user-images.githubusercontent.com/26760571/105835682-c3f12b80-5fd4-11eb-85fe-6082badadf09.png)

One plugin has `plugin` in the middle:
![image](https://user-images.githubusercontent.com/26760571/105835720-d53a3800-5fd4-11eb-95d1-32dbf42b8b1e.png)

Some plugins have `title case` naming:
![image](https://user-images.githubusercontent.com/26760571/105835764-ea16cb80-5fd4-11eb-84cf-c498b94ae7f9.png)

Some don't:
![image](https://user-images.githubusercontent.com/26760571/105835778-f1d67000-5fd4-11eb-80fc-39619d753a30.png)

We should have a consistent naming convention, thoughts?

**Comment by ehmicky** [comment]
Your approach in #209 looks great :+1:

**Comment by iKristy** [comment]
Love this initiative! Thank you for this. Cc'ing @rstavchansky as I bet it would be useful to get content eyes on this 👀 

Also, if I can drop my 2c on this: personally I'm not a big fan of title case, so if there is a choice, I would prefer keeping sentence case.

**Comment by verythorough** [comment]
Thanks for doing this! Agreed on the sentence case preference, as that's more consistent with the rest of our UI.
