### ISSUE TITLE
How to account for plugins "removed" from the list

### ISSUE THREAD

**Issue by verythorough** [netlify/plugins#28]
The list of plugins in plugins.json populates the list of plugins in the Netlify UI. Sometimes, plugins will have to be removed, for example, if the plugin stops working, stops meeting the guidelines (#20), or is unpublished from npm.

We could just remove the plugin from the json list, but there are instances where we might still want information about the plugin available - for example, to display currently installed plugins in the UI.

One way to do this would be to add an `"active": false` field to an inactive plugin. (I'd say `"inactive": true`, but I hesitate because double negatives can be tricky.) When a plugin has that field, I think we might also want to:
- Change the `name` to `Some Plugin Name (inactive)`, so another author might be able to add a new plugin called `Some Plugin Name`.
- Remove the `repo` URL, or account for the fact that it may no longer exist or be useful.
- Change or remove other fields?

Thoughts? cc @erquhart  @nasivuela @charliegerard  @ehmicky

**Comment by ehmicky** [comment]
Sounds good! :+1:

**Comment by erquhart** [comment]
[Requirements](https://www.notion.so/netlify/Product-Design-One-Click-Installs-87deb00a1b204409a06c8b4b23b187ae#bbbd6ca807be4231803fe4eddc7b6535) have a `status` property for this purpose:

> status - a field that accepts a status string, initially with simple boolean states like OK (which should probably the default) and DISABLED for quickly removing a plugin from our UI without removing it entirely from the repo, could also be used for specific security or usability statuses in the future
