### ISSUE TITLE
Document/communicate to plugin authors the new release process

### ISSUE THREAD

**Issue by ehmicky** [netlify/plugins#29]
We will soon lock plugin versions (#27), which means new ones will need to go through a PR and code review process. 

We should document this in `netlify/build` and `netlify/plugins` `README.md`.

Any thoughts?

@verythorough @mheffner @erquhart

**Comment by erquhart** [comment]
- @ehmicky you and @erezrokah can be primaries for general approval, and can pull in backend or support when needed
- @verythorough and I can approve from a product ownership perspective
- A new plugin should have both kinds of approval (at least for this initial process)

We should have a CODEOWNERS file set up to codify these approval requirements.

**Comment by erezrokah** [comment]
We should probably have a standard flow of approving a plugin.

1. Install plugin locally
2. Check source code and published code
3. Test for both functionality and security

On that note, how much damage a bad plugin can cause? Can plugins commit to the repo?
