### ISSUE TITLE
"Read plugin docs" button assumes that a `README.md` file exists

### ISSUE THREAD

**Issue by pizzafox** [netlify/plugins#59]
Clicking this button takes you to the repository for a Netlify build plugin and views the file `README.md`. 

![Screenshot](https://zws.im/‍‍‌‌‍‍‌‍‍‌‌‍‍‍‍‌)

I noticed that clicking this button on one of my plugins has a 404 page from GitHub. I believe my filenames should not shout at me, and as such I don't have a `README.md` file, but rather a `readme.md` file.

It looks like the link is assuming that there is a `README.md` file, but you should probably be using the `#readme` element on all GitHub repositories:
```diff
-https://github.com/user/repo/blob/master/README.md
+https://github.com/user/repo#readme
```

**Comment by ehmicky** [comment]
@nasivuela @charliegerard

**Comment by nasivuela** [comment]
Thanks for reporting @pizzafox . Fixed!
