### ISSUE TITLE
Incorporate npm diff checking into plugin update process

### ISSUE THREAD

**Issue by erquhart** [netlify/plugins#69]
We can use npm diffs to:
- ensure the version in the PR is actually published
- see the code differences between the current version and the proposed update version

Two solutions:
- Web based: https://diff.intrinsic.com/
- Programmatic: https://github.com/juliangruber/npm-diff

Two ways to do this:
- Easy/quick: add a "Diff" line to the issue template requesting an intrinsic diff link, Eg., https://diff.intrinsic.com/netlify-plugin-cypress/1.3.9/1.3.11
- Automated: use a GH check/app/etc to provide the link or diff when a PR is opened

**Comment by ehmicky** [comment]
Manual approach done at #70.
Automated approach might be better though once we have some time.

**Comment by erquhart** [comment]
Might not even be necessary, link is very simple for plugin authors to provide.
