### ISSUE TITLE
Plugins data

### ISSUE THREAD

**Issue by ehmicky** [netlify/plugins#78]
Every time a build has run, we collect, for each plugin, the following information in an anonymous way, as part of the `plugin_runs` API endpoint:
  - name of the plugin
  - version of the plugin
  - whether the plugin has succeeded or failed (with a further distinction between `cancelBuild` vs `failPlugin` vs `failBuild`)

This information is very useful because it allows us to have precise information (per build, site or account) about:
  - usage of each plugin
  - error rate of each plugin
  - whether some users got stuck on previous versions of specific plugins (when installed in their `package.json`)

There are some additional information that we are not sending but easily could:
  - whether the plugin was installed through the UI, `netlify.toml`, `netlify.toml` combined with `package.json`, automatically installed, loaded from build image cache, etc.
  - most used events by plugins

This in turns can be used in several ways:
  - exposed to users to help them choose to use or not plugins: displayed in the UI, used to sort the plugins list, etc.
  - internally to enrich our dashboards to get a good understanding of plugin usage, similar to https://cloud.us.humio.com/netlify-us-production/dashboards/JkRVXoKilcjr98MuMBZW9KPRakOXr4Mc

Since we already have this data, it might be interesting to discuss what can be done with it.

@verythorough @erquhart @seldo

**Comment by verythorough** [comment]
Closing because we're now using this data in a variety of ways, and also have multiple data issues on the subject.
